### ISSUE TITLE
Flow for building manual with xdvipdfmx breaks

### ISSUE THREAD

**Issue by piquan** [ascherer/cwebbin#10]
If the build is set to use `dvipdfm` (the default) instead of `pdftex`, the build stage for `fullmanual` will fail.  It will run `dvipdfm ctangle`, which will try to load the `ctangle` executable in the current directory, instead of `ctangle.dvi`.

(Note: In Debian-based distros, the default version of `dvipdfm` is `xdvipdfmx`; I don't know if this following is a problem under stock `dvipdfm`.)

```
ctangle -> ctangle.pdf
DVI ID = 0

xdvipdfmx:fatal: Something is wrong. Are you sure this is a DVI file?

Output file removed.
Makefile.unix:212: recipe for target 'ctangle.pdf' failed
make[1]: Leaving directory '/tmp/cwebbin-cwebbin-22p'
make[1]: *** [ctangle.pdf] Error 1
make: *** [fullmanual] Error 2
Makefile.unix:309: recipe for target 'fullmanual' failed
The command '/bin/sh -c make -f Makefile.unix all' returned a non-zero code: 2
```

The repro I used for this is in https://gist.github.com/piquan/937fbc682090838870210af996102e85 , along with a patch for both this issue and #9 (which shadows this issue in that repro).  To reproduce the dvipdfm issue being described here, delete the part of `cwebbin.diff` starting from `@@ -210,7 +210,7 @@` onwards.

**Comment by ascherer** [comment]
TeXlive's `dvipdfm` is a symlink to `xdvipdfmx`, which tries to process the local `ctangle` executable instead of the expected `ctangle.dvi` file. (As for now, `pdftex` works as expected.)

**Comment by ascherer** [comment]
**Rollback imminent!** — The authors of `xdvipdfmx` have agreed to restore the canonical behavior of TeXlive programs, similar to `tex`, `pdftex`, `dvipdf`, and (antique) `dvipdfm`, so that with the next update of `xdvipdfmx` it is not necessary to add the default file suffix. Unless DEK makes a similar change upstream in CWEB, I'll roll back the change in CWEBbin RSN.

**Comment by piquan** [comment]
I have no objection to you rolling back.  I don’t know the relationship that exists, or is desired, among DEK, the authors of various extensions (like Lamport), and the maintainers of TeΧlive, and the maintainers of the Linux distros, so I don’t pretend to know the assumptions that are appropriate for you to make.

That said, if this were a typical program that you might find in Linux (rather than a TeΧ-based program with DEK’s blessing), I might argue that a rollback should wait until the change bubbles down to releases of the major Debian-based distros like Mint and Ubuntu.  As I understand it, `Makefile.unix` is meant to compensate for some of the (ahem) differences between Unices, and the change (I’m guessing) is compatible with both `xdvipdfmx`’s way of handling extensions and `dvipdfm`’s.  So if you’re going for practicality, it might be best to always include the `.dvi` extension.

Again, I really don’t know what the desired goals of cwebbin are, so I don’t pretend to say that you should do things one way or the other.  I’m just presenting a counterargument for you to consider as you work on it.  Either way, I can manage my own task (which was just to get a manual for cwebbin).

**Comment by ascherer** [comment]
@piquan Good point. At least I'll inform DEK of the upcoming change in `xdvipdfmx`; he's extremely reluctant to adapt his software to such idiosynchracies, so I don't think that CWEB's Makefile will be modified. However, from the discussion on [the tex-k list](https://tug.org/pipermail/tex-k/2018-May/thread.html#2882) `xdvipdfmx`will learn the conventions of TeXlive soon. I'm aware that it takes a long time for Linux distributions to catch up (if ever).
