### ISSUE TITLE
Integrate HyperCWEB

### ISSUE THREAD

**Issue by ascherer** [ascherer/cwebbin#22]
See [HyperCWEB](https://github.com/ascherer/cwebbin/tree/hyper-sync-tex) branch.

**Comment by ascherer** [comment]
See also [cweb-git](https://github.com/igor-liferenko/cweb-git).

**Comment by igor-liferenko** [comment]
It moved to [cweb](https://github.com/igor-liferenko/cweb).

**Comment by ascherer** [comment]
I close this issue, because (a) I only rarely use `dvi` output and (b) virtually never use XDVI.
