### ISSUE TITLE
Whatis entry in manual page of ctwill / cweb

### ISSUE THREAD

**Issue by hpreusse** [ascherer/cwebbin#41]
This is rather a question than a bug report. I just build the Debian package providing the Debian binaries. For the manual pages of `ctwill` & `cweb` [it complains](https://lintian.debian.org/sources/texlive-bin/2020.20200327.54578-4.html):

```
W: bad-whatis-entry usr/share/man/man1/ctwill.1.gz
W: bad-whatis-entry usr/share/man/man1/cweb.1.gz
```
Indeed the entry behind `.SH NAME` is empty or separated from the expected content by `.PP`. The manual pages are generated by pandoc, hence it could be a bug in pandoc, not generating the manual page correctly. Could you have a short look if it is an issue in the md file or in pandoc? Thanks!

**Comment by ascherer** [comment]
Most likely, I'll have to change `--` to `-` in the `.md` files. `--` gets rendered as `\[en]`, but **man-pages** seems to _require_ `\-` at this point.

**Comment by ascherer** [comment]
However, even if I used single hyphens `-` in the `.md` files, `pandoc -t man` still would not create minus `\-` in the manpages. See [the Pandoc demos page](https://pandoc.org/demos.html): the generic input [pandoc.1.md](https://pandoc.org/demo/pandoc.1.md) gets rendered as [example10.1](https://pandoc.org/demo/example10.1) _without_ the backslash required by [man(7)](https://man7.org/linux/man-pages/man7/man.7.html).

**Comment by ascherer** [comment]
After fiddling with `mandb` on the TeX Live tree, `whatis ctwill` correctly prints the relevant index entry (also `whatis cweb` etc.).  Thanks for pointing this out.  (Feel free to open an issue for Pandoc.)
