### ISSUE TITLE
Can/will/should there be support for future ISO C language features?

### ISSUE THREAD

**Issue by texdraft** [ascherer/cwebbin#46]
Occasionally I like to check the [publicly-available documents of ISO Working Group
14](http://www.open-std.org/jtc1/sc22/wg14/www/docs/) to see what's new in the world of C.
There you can find various proposals and draft standards, the most recent one being
[N2596](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2596.pdf). Most of the changes
are in semantics or in the standard library, but I was surprised to find that the syntax
of the language has been extended in two significant ways.

Even though this is a draft standard, it is a close approximation to what the next
official one will be. I'll use the present tense to be more understandable.

First, C now has binary integer literals, written with a `0b` (or `0B`) prefix, as in
`0b101010`. They were proposed in [document
N2549](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2549.pdf). This syntax is also
present in C++.

The more interesting change was in the introduction of “attributes”, based on a
recently-added C++ feature. They were proposed in [document
N2335](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2335.pdf). Attributes have the
general form of an identifier surrounded by double square brackets, as in `[[whatever]]`.
Sometimes they can have a parenthesized argument after the identifier.  They behave
somewhat like GCC's `__attribute__`, but of course they are standardized. Here is an
example of an attribute, based on paragraph 6.7.11.3.5 of the draft linked above:

```C
int f(int i) {
      [[maybe_unused]] int j = i + 100;
      assert(j);
      return i;
}
```

The code declares that variable `j` might be unused; the implementation should not produce
a warning if it isn't. (It will be unused if `NDEBUG` is defined, so that `assert` expands
to `((void)0)`.) Thus it's basically like Common Lisp's `(declare (ignore ...))`.

The standard attributes currently defined are `nodiscard` (discourage use of value in void
expression), `deprecated` (indicate that something isn't to be used), `fallthrough`
(indicate that control in a `switch` statement is intended to fall through from one `case`
to another), and `maybe_unused` (indicate that something may not be used).

Unfortunately for those who want to cross-reference C code, attributes can appear in
troubling places. Here is the standard's example for the `deprecated` attribute
(6.7.11.4.7):

```C
struct [[deprecated]] S {
      int a;
};

enum [[deprecated]] E1 {
      one
};

enum E2 {
      two [[deprecated("use ’three’ instead")]],
      three
};

[[deprecated]] typedef int Foo;

void f1(struct S s) { // Diagnose use of S
      int i = one; // Diagnose use of E1
      int j = two; // Diagnose use of two: "use ’three’ instead"
      int k = three;
      Foo f; // Diagnose use of Foo
}

[[deprecated]] void f2(struct S s) {
      int i = one;
      int j = two;
      int k = three;
      Foo f;
}

struct [[deprecated]] T {
      Foo f;
      struct S s;
};
```

The attribute appears before a declaration (`Foo`, `f2`), in the middle of a declaration
(`S`, `E1`, `T`), and after an enumeration constant in an `enum` declaration (`E2`). Note
that, syntactically, the grammar of the standard says that the attributes are actually a
part of the declaration.

Implementing binary literals in `CWEAVE` and `CTANGLE` is trivial, although the default
formatting of such constants would have to be decided upon. I don't think any changes to
`CTANGLE` are necessary to implement attributes. `CWEAVE` is another story. Getting them
to format correctly probably wouldn't be a huge challenge, but I believe there may be
problems with the indexing code. Specifically, when an identifier is to be underlined or
made reserved, `find_first_ident` is called; this function would find the attribute and
return it instead of the intended token.

One fix would be to make attributes a special case and “give up”, as `CWEAVE` does with
C++'s `operator`. Or they could be ignored in the search. Either way, the existing logic
could produce anomalous results.

I am not requesting that these changes be made, but rather asking whether these changes,
and any similar ones, *should* be made. (If so, then I would be happy to write the code
myself.) Maybe it is desired to keep the syntax to C99. Adding binary literals and
attributes would have the plus side of improving support for C++, if that means anything.
Other syntactic elements of (published recent standards of) C and C++ that `CWEB` doesn't
handle are the use of “universal character names” (e.g., `x\U3401y`) and string/character
constant encoding prefixes (e.g., `U8"whatever"`). Logically, I think, the prefix should
be written in typewriter style along with the rest of the string.

Thank you for your hard work in making this wonderful program more accessible.

**Comment by ascherer** [comment]
`CWEB` **4.x** has learned about `U8` and other prefixes. And `CWEB` in “TeX Live” has known about these prefixes since 2019(?).

I'll call back about the other points ASAP.  Of course, better support for more recent dialects of C/C++ is very welcome; see, e.g., [this issue](https://github.com/ascherer/cweb/issues/17). Current devopment is done in [this branch](https://github.com/ascherer/cweb/tree/cweb-4.3-dev).

**Comment by texdraft** [comment]
You're completely right about the prefixes. Sorry, I misremembered.
