### ISSUE TITLE
texlive's cweave does not work for a certain file

### ISSUE THREAD

**Issue by sjnam** [ascherer/cwebbin#62]
Hello,

cweave which version is `CWEAVE 4.7 (TeX Live 2022)` doesn't work for
https://www-cs-faculty.stanford.edu/~knuth/programs/ssxc0.w file.

After cweave, doing tex has the following error message
```
This is TeX, Version 3.141592653 (TeX Live 2022) (preloaded format=tex)
(./ssxc0.tex (/usr/local/texlive/2022/texmf-dist/tex/plain/cweb/cwebmac.tex
(/usr/local/texlive/2022/texmf-dist/tex/generic/iftex/iftex.sty)) *1
! Missing $ inserted.
<inserted text>
                $
<to be read again>
                   \nonscript
\Xmod ->\nonscript
                   \mskip -\medmuskip \mkern 5mu \mathbin {\rm mod}\penalty ...
l.39 \B\4\D\Xmod
                \5
?
```

but Knuth's original cweb(ftp://ftp.cs.stanford.edu/pub/cweb/cweb.tar.gz) works fine.

Thank you.

**Comment by ascherer** [comment]
This affects at least `back-graceful-kmp3.w`, `dlx1.w`, `dlx2.w`, `dlx3.w`, `dlx5.w`, `dlx6.w`, `sat13.w`, `ssxc0.w`, `ssxc1.w`, `ssxcc0.w`, `ssxcc1.w`, `ssxcc2.w`, `ssxccdom.w`.

**Comment by ascherer** [comment]
This commit is at fault: https://github.com/ascherer/cweb/commit/56d37fb32a78666d0692601437731735a22a9236

**Comment by ascherer** [comment]
Fixed in TL source tree (and in upstream CWEB 4.9).
