### ISSUE TITLE
Bootstrapping issue: cannot find @i files during initial compile

### ISSUE THREAD

**Issue by piquan** [ascherer/cwebbin#9]
While doing an initial build of cwebbin, I run into a problem: while it's running `ctangle`, it's looking for the `@i` files in the installed location, not at the ones in the build tree.  That means that if cwebbin isn't yet installed, it can't build itself.

```
./ctangle +s ctangle ctang-22p.ch ctangle.cxx
This is CTANGLE (Version 3.64 [22p])
*1
! Cannot open include file. (l. 26 of include file comm-22p.h)
@i iso_types.w
```

An example Dockerfile showing the workflow that led up to this is in https://gist.github.com/piquan/937fbc682090838870210af996102e85 .  There's also a patch in that gist that fixes both this issue and #10.

**Comment by ascherer** [comment]
Thanks for pointing this out.
